apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quest-guestbook-01
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: quest-guestbook-01
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: helm-guestbook
    targetRevision: master
  syncPolicy:
    automated: {}